config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "users/registrations" }

  resources :users do
    resources :posts
  end

  resources :users do
    resources :follows
  end 

  resources :posts do
    resources :likes
    resources :comments
  end

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
    validates :body, presence: true

    has_many :comments, dependent: :destroy
    has_many :likes, foreign_key: :liked_post_id, dependent: :destroy
    has_many :users_who_liked_this, through: :likes, source: :liking_user, dependent: :destroy
    belongs_to :author, foreign_key: :author_id, class_name: "User"
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!

    def index
        @posts = Post.all 
    end

    def new 
        @post = Post.new
    end

    def show
        @post = Post.find(params[:id])
    end

    def create
        @user = User.find(params[:post][:author_id])
        @post = @user.authored_posts.build(post_params)

        respond_to do |format|
            if @post.save
                format.turbo_stream
            else
                format.html {render :new, status: :unprocessable_entity}
            end
        end 
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update 
        @post = Post.find(params[:id])
        @post.update(post_params)

        if @post.save
            redirect_to @post, status: :see_other
        else 
            render :edit, status: :unprocessable_entity
        end
       
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        
        redirect_to :root, status: :see_other
      end

    private
    def post_params
        params.require(:post).permit(:body,:author_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<form action="/posts" method="post" >
    <div data-controller='hello'>
    <textarea id='post[body]' name='post[body]' type='text_area' data-hello-target='post'></textarea>
    <input id='post[author_id]' name='post[author_id]' type='hidden' value="<%= current_user.id %>" /><br>
    <input type='submit' value='Create post' data-action="hello#clear"/>
    </div>
</form>

app/views/posts/_post.html.erb
<div>
    <ul class='list_item'>
    <li><h3><strong><%= post.body %></h3></strong></li>
    </ul>
    <div><%= link_to 'See post', user_post_path(post.author.id,post.id)%></div><br>
    <%= turbo_frame_tag 'comments' do%>
    <div><%=link_to 'See comments', post_comments_path(post.id)%></div>
    <% end %>
</div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.append "posts", @post %>

app/views/posts/edit.html.erb
<%= turbo_frame_tag @post do %>
    <h1> Edit post </h1>
    <%= render "form", post: @post %>
    <%= link_to "Return to post", @post, data: { turbo_frame: "_top" } %>
<% end %>

app/views/posts/index.html.erb
<div class='index'>
  <div class='new_post'>
    <%= turbo_frame_tag id="new_post", src:new_post_path %>
  </div>

  <div id="posts" class='posts'>
    <%= render @posts %>
  </div><br>

  <div class='follows'>
    <h3> Users you follow: </h3>
    <% current_user.given_follows.each do |f|  %>
        <ul>
        <li><%= f.followed_user.name %></li>
        </ul>
    <% end %>
  </div>


</div>

app/views/posts/new.html.erb
<%= turbo_frame_tag 'new_post' do%>
    <h1> Create post </h1>

    <%= render "form", post: @post %><br>
<% end %>

app/views/posts/show.html.erb
<h2> Post </h2>
<%= @post.body %>
<%= turbo_frame_tag 'author', src: user_path(@post.author.id) do %>
    <div></div>
<% end %>
<h2> Comments </h2>
<div id='comments'><%= render @post.comments%></div>
<h2> Users who liked this post: </h2>
<div><%= render @post.likes%></div>
<%= render "likes/form" %>
<%= render "comments/form" %>

<% if @post.author.id == current_user.id %>
    <%= turbo_frame_tag @post do %>
        <div><%= link_to 'Edit post', edit_user_post_path(@post.author.id,@post.id) %></div>
    <% end %>
    <div><%= link_to 'Delete post', user_post_path(@post.author.id,@post.id), data: { turbo_method: :delete,
                                                                                    turbo_confirm: "Are you sure?"
                                                                                    } %></div>
<% end %>


<div><%= link_to 'Home',root_path %></div>